### ISSUE TITLE
issue with banker

### ISSUE THREAD

**Issue by tirzah2** [fantasycalendar/FoundryVTT-ItemPiles-Bankers#1]
Hi!
i installed today the item piles bankers, and i have a strange issue. My first player created the vault, and it worked. Then the other players when they tried, instead of asking them to create a new vault and pay 50gp, it just opened the vault of the first player. 

have i done something wrong?

**Comment by Haxxer** [comment]
This doesn't happen to me, could you upload a video of this happening?

**Comment by tirzah2** [comment]
Hi Haxxer, i hope it make sense. first i create the banker, then i login with another player, create the vault, then i login with a third player, and the third player see the bank vault of the first one without asking if he wants a vault opened. 
https://www.dropbox.com/t/lfSc1TnG1uvzKGb7

**Comment by Haxxer** [comment]
Strange. Please provide the following:

- Foundry Version: [e.g. 9.238]
- System & Version: [e.g. DND5e 1.5.7]
- Item Piles Version: [e.g. 1.0.0]
- Item Piles: Bankers Version: [e.g. 1.0.0]

**Comment by tirzah2** [comment]
Foundry Virtual Tabletop: Version 11 Stable, 11.304
Game System: dnd5e, 2.2.2
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/83312683/cadf0b60-ba03-48e6-9422-2f0ccec4b705)

**Comment by Haxxer** [comment]
This is my current setup of the banker, what does yours look like?

![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/12858387/bce31eeb-9bbd-40f9-88c0-35871c4764ff)

**Comment by tirzah2** [comment]
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/83312683/08868cfc-84af-457b-ad5a-0ffc719a9d17)

**Comment by tirzah2** [comment]
i even created a new player and a new user, bbb (player35), just to make sure there was no issue with my current players. But no, even bbb when he opens the banker sees Aurio's Bank (the first player that opened an account)
![image](https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/83312683/8fa9d50d-8cd2-47aa-b305-daf0cf126092)

**Comment by Haxxer** [comment]
To help you further, I'd need to take a look in your server to see what's going wrong - contact me on Discord, my username is `wasp`
