### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by dylanwalton18** [fantasycalendar/FoundryVTT-ItemPiles-Bankers#2]
I tried to install it today and it gave me an error when I tried to apply the manifest URL.

**Comment by dylanwalton18** [comment]
<img width="1276" alt="Screenshot 2024-05-29 at 3 12 34 PM" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/70955024/0ce4d343-6650-47bc-8a3f-2b9b44ff57a1">

**Comment by ianglang** [comment]
same for me.

**Comment by kmdavis** [comment]
looks like it's now https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/releases/latest/download/module.json
but it doesn't support Foundry v12 yet

<img width="996" alt="Screenshot 2024-07-10 at 10 28 14 PM" src="https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/assets/132806/3a2aa0b4-e0fb-4c98-b8cc-a6b2d06aa556">

**Comment by Haxxer** [comment]
Fixed
