### ISSUE TITLE
Error 404: manifest.json Not Found

### ISSUE THREAD

**Issue by shuanz** [fantasycalendar/FoundryVTT-ItemPiles-Bankers#3]
Hello,

I am encountering an issue when trying to access the manifest.json file from the following URL:

`https://github.com/fantasycalendar/FoundryVTT-Bankers/releases/latest/download/manifest.json
`

The URL returns the following error:

`{
  "error": "Not Found"
}
`

It seems that the file might be missing or the URL may be incorrect. Could you please check and resolve this issue?

Thank you for your attention to this matter.

**Comment by Haxxer** [comment]
Try module.json. these can be found in the releases of GitHub.

**Comment by shuanz** [comment]
Thank you, @Haxxer, for the suggestion!

I tried using the link you provided, and I was successful with the following URL:

`https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/releases/download/1.1.0/module.json`

I appreciate your help!

**Comment by shuanz** [comment]
The issue was resolved by using the URL for the module.json file, specifying the version from the releases. Here's the format that worked:

`https://github.com/fantasycalendar/FoundryVTT-ItemPiles-Bankers/releases/download/[version]/module.json
`
